"""create llm_events and model_prices

Revision ID: 0001
Revises:
Create Date: 2026-07-03 20:02:54.336620

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=True),
        sa.Column("raw_usage", sa.JSON(), nullable=False),
        sa.Column("price_snapshot", sa.JSON(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("prompt_hash", sa.String(), nullable=True),
        sa.Column("project", sa.String(), nullable=True),
        sa.Column("feature", sa.String(), nullable=True),
        sa.Column("env", sa.String(), nullable=True),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("customer", sa.String(), nullable=True),
        sa.Column("tags", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("provider_request_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_events")),
    )
    with op.batch_alter_table("llm_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_events_feature"), ["feature"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_events_model"), ["model"], unique=False)
        batch_op.create_index("ix_llm_events_model_ts", ["model", "ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_events_project"), ["project"], unique=False)
        batch_op.create_index("ix_llm_events_project_ts", ["project", "ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_llm_events_prompt_hash"), ["prompt_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_llm_events_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_events_ts"), ["ts"], unique=False)

    op.create_table(
        "model_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("input_per_mtok", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("output_per_mtok", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cache_read_per_mtok", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("cache_write_per_mtok", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("last_verified", sa.Date(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_prices")),
        sa.UniqueConstraint("provider", "model", name=op.f("uq_model_prices_provider_model")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_prices")
    with op.batch_alter_table("llm_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_events_ts"))
        batch_op.drop_index(batch_op.f("ix_llm_events_run_id"))
        batch_op.drop_index(batch_op.f("ix_llm_events_prompt_hash"))
        batch_op.drop_index("ix_llm_events_project_ts")
        batch_op.drop_index(batch_op.f("ix_llm_events_project"))
        batch_op.drop_index("ix_llm_events_model_ts")
        batch_op.drop_index(batch_op.f("ix_llm_events_model"))
        batch_op.drop_index(batch_op.f("ix_llm_events_feature"))

    op.drop_table("llm_events")
    # ### end Alembic commands ###
