"""add first_token_ms to llm_events

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-04 10:23:15.720119

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_token_ms", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_events", schema=None) as batch_op:
        batch_op.drop_column("first_token_ms")

    # ### end Alembic commands ###
